### ISSUE TITLE
Multiple views of the same name are not differentiated well

### ISSUE THREAD

**Issue by igorkulman** [hmemcpy/ReSharper.Xao#19]
Thanks for fixing #8 but it does not work perfectly yet in a Universal Windows 8.1 + Windows Phone 8.1 project. See the screenshot

![image](https://cloud.githubusercontent.com/assets/4746070/21849725/8796e1f6-d807-11e6-9c7d-08dc5f728c58.png)

The first `LoginView` is in AlzaMedia.WindowsPhone project but "AlzaMedia.WindowsPhone" is not shown there. The second  `LoginView` shows correctly in AlzaMedia.Windows project.

**Comment by akarpov89** [comment]
Hi @igorkulman,

Currently by design suffix "(in <project_name>)" is added only if the related file is located in the project other than current. I'm wondering if this is your case?

**Comment by igorkulman** [comment]
Then it is fine, it was the current project. I just did not expect it working like this :)
