### ISSUE TITLE
Showing strange stuff

### ISSUE THREAD

**Issue by igorkulman** [hmemcpy/ReSharper.Xao#9]
In one project, the extensions show some strange stuff, like images:

![clipboard01](https://cloud.githubusercontent.com/assets/4746070/9578982/ef26e822-4fee-11e5-8cfb-442cf06c9499.png)

**Comment by hmemcpy** [comment]
Yikes! Just to rule that out, does it show without Xao?
What kind of items are these? Are they referenced anywhere inside the xaml?

**Comment by igorkulman** [comment]
The images are referenced in a DataTemplate in XAML and are also shown without Xao. So another VS bug I guess, sorry to blame you :)

**Comment by hmemcpy** [comment]
Heh, no problem at all :) You might want to let @controlflow know about it, he loves XAML bugs :)

**Comment by hmemcpy** [comment]
But perhaps it's a feature: those files *are* related to the view, so...
